// Code generated by "stringer -type=ExtentKind -trimprefix=Extent"; DO NOT EDIT.

package keel

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ExtentFixed-0]
	_ = x[ExtentFlex-1]
}

const _ExtentKind_name = "FixedFlex"

var _ExtentKind_index = [...]uint8{0, 5, 9}

func (i ExtentKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ExtentKind_index)-1 {
		return "ExtentKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExtentKind_name[_ExtentKind_index[idx]:_ExtentKind_index[idx+1]]
}
