// Code generated by "stringer -type=FitMode -trimprefix=Fit"; DO NOT EDIT.

package keel

import "strconv"

func _() {
	var x [1]struct{}
	_ = x[FitExact-0]
	_ = x[FitWrapClip-1]
	_ = x[FitWrapStrict-2]
	_ = x[FitClip-3]
	_ = x[FitOverflow-4]
}

const _FitMode_name = "ExactWrapClipWrapStrictClipOverflow"

var _FitMode_index = [...]uint8{0, 5, 13, 23, 27, 35}

func (i FitMode) String() string {
	if i < 0 || i >= FitMode(len(_FitMode_index)-1) {
		return "FitMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FitMode_name[_FitMode_index[i]:_FitMode_index[i+1]]
}
