// Code generated by "stringer -type=NodeKind"; DO NOT EDIT.

package keel

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NodeContent-0]
	_ = x[NodeContainer-1]
}

const _NodeKind_name = "NodeContentNodeContainer"

var _NodeKind_index = [...]uint8{0, 11, 24}

func (i NodeKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_NodeKind_index)-1 {
		return "NodeKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NodeKind_name[_NodeKind_index[idx]:_NodeKind_index[idx+1]]
}
