// Code generated by "stringer -type=SizeKind"; DO NOT EDIT.

package keel

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SizeFixed-0]
	_ = x[SizeFlex-1]
}

const _SizeKind_name = "SizeFixedSizeFlex"

var _SizeKind_index = [...]uint8{0, 9, 17}

func (i SizeKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_SizeKind_index)-1 {
		return "SizeKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SizeKind_name[_SizeKind_index[idx]:_SizeKind_index[idx+1]]
}
