// Code generated by "stringer -type=Axis -trimprefix=Axis"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AxisHorizontal-0]
	_ = x[AxisVertical-1]
}

const _Axis_name = "HorizontalVertical"

var _Axis_index = [...]uint8{0, 10, 18}

func (i Axis) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Axis_index)-1 {
		return "Axis(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Axis_name[_Axis_index[idx]:_Axis_index[idx+1]]
}
